// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBdb1iBbTRMR9HTVl3t9ALmstm8SUYXwE',
    appId: '1:660171371502:web:f59aa59c0d84f5bd1b94ff',
    messagingSenderId: '660171371502',
    projectId: 'shayari-0',
    authDomain: 'shayari-0.firebaseapp.com',
    storageBucket: 'shayari-0.firebasestorage.app',
    measurementId: 'G-YY9GWZV9PZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWGq4osXqK2EIulRbDR2QQtL597Qv5VXI',
    appId: '1:660171371502:android:79c9c5a824d58e411b94ff',
    messagingSenderId: '660171371502',
    projectId: 'shayari-0',
    storageBucket: 'shayari-0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcZShjs0fMY2SmV9iYtrvu8P2gXBr4STk',
    appId: '1:660171371502:ios:b693f5c2d46981051b94ff',
    messagingSenderId: '660171371502',
    projectId: 'shayari-0',
    storageBucket: 'shayari-0.firebasestorage.app',
    iosBundleId: 'com.example.shayariApp',
  );
}
